import './global.css';
// import { UiLayout } from '@/components/ui/ui-layout';
import { ClusterProvider } from '@/components/cluster/cluster-data-access';
import { SolanaProvider } from '@/components/solana/solana-provider';
import { ReactQueryProvider } from './react-query-provider';
import { NextUIProvider } from '@nextui-org/react';
import LayoutComponent from '@/components/LayoutComponent';
import { signIn, signOut } from '@/auth';

export const metadata = {
  title: 'round3',
  description: 'Generated by create-solana-dapp',
};

const links: { label: string; path: string }[] = [
  { label: 'Account', path: '/account' },
  { label: 'Clusters', path: '/clusters' },
  { label: 'Round3 Program', path: '/round3' },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <form
          action={async (formData) => {
            'use server';
            await signIn('credentials', formData);
            await signOut();
          }}
        >
          <label>
            Wallet address
            <input name="walletAddress" />
          </label>
          <button>Sign In</button>
        </form>
        <ReactQueryProvider>
          <ClusterProvider>
            <SolanaProvider>
              <NextUIProvider>
                {/* <UiLayout links={links}>{children}</UiLayout> */}
                <LayoutComponent>{children}</LayoutComponent>
              </NextUIProvider>
            </SolanaProvider>
          </ClusterProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
